/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;
import javax.swing.table.DefaultTableModel;
import pengukuran_kayu.Rekap; 

/**
 *
 * @author Vivobook
 */
public class FrameKayu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameKayu.class.getName());
    Rekap dataKayu;

    /**
     * Creates new form FrameKayu
     */

    
    public FrameKayu(){
        initComponents();
        this.setLocationRelativeTo(null);
        dataKayu = new Rekap();
        tampilDataKayu();
    }
    
    public void tampilDataKayu() {
    DefaultTableModel kayuModel = new DefaultTableModel();
    kayuModel.addColumn("Nama Kayu");
    kayuModel.addColumn("No Kayu");
    kayuModel.addColumn("Panjang (m)");
    kayuModel.addColumn("Diameter Ujung (cm)");
    kayuModel.addColumn("Diameter Pangkal (cm)");
    kayuModel.addColumn("Diameter Rata (cm)");
    kayuModel.addColumn("Volume (m3)");
    kayuModel.addColumn("Jumlah Kayu");
    kayuModel.addColumn("Keterangan");

        for (int i = 0; i < dataKayu.listDataNama().size(); i++) {
            String nama    = dataKayu.listDataNama().get(i);
            int no         = dataKayu.listDataNoKayu().get(i);
            double panjang = dataKayu.listDataPanjang().get(i);
            double dUjung  = dataKayu.listDataDiameterUjung().get(i);
            double dPangkal= dataKayu.listDataDiameterPangkal().get(i);
            double dRata = dataKayu.listDataDiameterRata().get(i);
            double volume = dataKayu.listDataVolume().get(i);
            int jumlah = dataKayu.listDataJumlahKayu().get(i);
            String ket = dataKayu.listDataKeterangan().get(i);

            Object[] baris = {nama, no, panjang, dUjung, dPangkal, dRata,volume,jumlah,ket};
            kayuModel.addRow(baris);
        }
        tblKayu.setModel(kayuModel);
        tblKayu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPanjang = new javax.swing.JTextField();
        txtDUjung = new javax.swing.JTextField();
        txtDPangkal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKayu = new javax.swing.JTable();
        txtNo = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kayu");

        jLabel2.setText("No. Kayu :");

        jLabel3.setText("Panjang (m)  :");

        jLabel4.setText("Nama Kayu :");

        jLabel5.setText("Diameter Pangkal (cm) :");

        jLabel6.setText("Diameter Ujung (cm) :");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        tblKayu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKayu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKayuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKayu);

        jLabel7.setText("Jumlah Kayu :");

        jLabel8.setText("Keterangan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDPangkal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPanjang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDUjung)
                            .addComponent(txtNama)
                            .addComponent(txtJumlah)
                            .addComponent(txtKeterangan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDUjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDPangkal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
           dataKayu.inputDataNama(txtNama.getText());
           dataKayu.inputDataNoKayu(Integer.parseInt(txtNo.getText()));
           dataKayu.inputDataPanjang(Double.parseDouble(txtPanjang.getText()));
           dataKayu.inputDataDiameterUjung(Double.parseDouble(txtDUjung.getText()));
           dataKayu.inputDataDiameterPangkal(Double.parseDouble(txtDPangkal.getText()));
           dataKayu.inputDataJumlahKayu(Integer.parseInt(txtJumlah.getText()));
           dataKayu.inputDataKeterangan( txtKeterangan.getText());
           
           dataKayu.setDUjung(Double.parseDouble(txtDUjung.getText()));
           dataKayu.setDPangkal(Double.parseDouble(txtDPangkal.getText()));
           dataKayu.setPanjang(Double.parseDouble(txtPanjang.getText()));
           double dr = dataKayu.hitungDiameterRata();
           double vol = dataKayu.hitungVolume();
           
           dataKayu.inputDataDiameterRata(dr);
           dataKayu.inputDataVolume(vol);
           tampilDataKayu();
        } catch (NumberFormatException e) {
           javax.swing.JOptionPane.showMessageDialog(null, "Input angka tidak valid!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblKayuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKayuMouseClicked
        int baris = tblKayu.getSelectedRow();
        txtNama.setText(tblKayu.getValueAt(baris, 0).toString());
        txtNo.setText(tblKayu.getValueAt(baris, 1).toString());
        txtPanjang.setText(tblKayu.getValueAt(baris, 2).toString());
        txtDUjung.setText(tblKayu.getValueAt(baris, 3).toString());
        txtDPangkal.setText(tblKayu.getValueAt(baris, 4).toString());
        txtJumlah.setText(tblKayu.getValueAt(baris,7).toString());
        txtKeterangan.setText(tblKayu.getValueAt(baris,8).toString());
    }//GEN-LAST:event_tblKayuMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        dataKayu.setDUjung(Double.parseDouble(txtDUjung.getText()));
        dataKayu.setDPangkal(Double.parseDouble(txtDPangkal.getText()));
        dataKayu.setPanjang(Double.parseDouble(txtPanjang.getText()));
        double dr = dataKayu.hitungDiameterRata();
        double vol = dataKayu.hitungVolume();

        dataKayu.ubahDataKayu(
        txtNama.getText(),
        Integer.parseInt(txtNo.getText()),
        Double.parseDouble(txtDUjung.getText()),
        Double.parseDouble(txtDPangkal.getText()),
        Double.parseDouble(txtPanjang.getText())
    );
        dataKayu.ubahDataRekap(
        Integer.parseInt(txtJumlah.getText()),
        txtKeterangan.getText(),
        dr,
        vol,
        txtNama.getText()
    );
        
    tampilDataKayu();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        dataKayu.hapusDataKayu(
        txtNama.getText(),
        Integer.parseInt(txtNo.getText()),
        Double.parseDouble(txtDUjung.getText()),
        Double.parseDouble(txtDPangkal.getText()),
        Double.parseDouble(txtPanjang.getText())
    );
        dataKayu.hapusDataRekap(txtNama.getText());
    tampilDataKayu();
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameKayu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKayu;
    private javax.swing.JTextField txtDPangkal;
    private javax.swing.JTextField txtDUjung;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtPanjang;
    // End of variables declaration//GEN-END:variables
}
